// Code generated by MockGen. DO NOT EDIT.
// Source: ./mocks/group.go
//
// Generated by this command:
//
//	mockgen -source ./mocks/group.go -destination=./mocks/group_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/khostya/effective-mobile/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgroupStorage is a mock of groupStorage interface.
type MockgroupStorage struct {
	ctrl     *gomock.Controller
	recorder *MockgroupStorageMockRecorder
	isgomock struct{}
}

// MockgroupStorageMockRecorder is the mock recorder for MockgroupStorage.
type MockgroupStorageMockRecorder struct {
	mock *MockgroupStorage
}

// NewMockgroupStorage creates a new mock instance.
func NewMockgroupStorage(ctrl *gomock.Controller) *MockgroupStorage {
	mock := &MockgroupStorage{ctrl: ctrl}
	mock.recorder = &MockgroupStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupStorage) EXPECT() *MockgroupStorageMockRecorder {
	return m.recorder
}

// CreateOnConflictDoNothing mocks base method.
func (m *MockgroupStorage) CreateOnConflictDoNothing(ctx context.Context, group domain.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnConflictDoNothing", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOnConflictDoNothing indicates an expected call of CreateOnConflictDoNothing.
func (mr *MockgroupStorageMockRecorder) CreateOnConflictDoNothing(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnConflictDoNothing", reflect.TypeOf((*MockgroupStorage)(nil).CreateOnConflictDoNothing), ctx, group)
}

// GetByID mocks base method.
func (m *MockgroupStorage) GetByID(ctx context.Context, title string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, title)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockgroupStorageMockRecorder) GetByID(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockgroupStorage)(nil).GetByID), ctx, title)
}
